name: orm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqfentity: ^2.4.0
  sqfentity_gen: ^2.3.0+4
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
